name: Aggiungi commits

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Forza aggiornamento
        run: |
          echo "Commit eseguito il $(date -u)" >> log.txt
          echo "Numero: $RANDOM" >> log.txt
          
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          
          git add log.txt
          git commit -m "Update $(date -u)" --allow-empty
          git push
