name: Commit Automatici

on:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Forza commit
        run: |
          echo "Commit del $(date -u +'%Y-%m-%d %H:%M:%S')" > commit.txt
          echo "Numero random: $RANDOM" >> commit.txt
          
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          
          git add commit.txt
          git commit -m "Auto commit $(date -u)" --allow-empty
          git push
